spring:
  cloud:
    compatibility-verifier:
      enabled: false
  datasource:
    primary:
      hikari:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: ${MYSQL_USERNAME}
        password: ${MYSQL_PASSWORD}
        jdbc-url: jdbc:mysql://localhost:3306/dapanda?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&autoReconnect=True
    secondary:
      hikari:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: ${MYSQL_USERNAME}
        password: ${MYSQL_PASSWORD}
        jdbc-url: jdbc:mysql://localhost:3306/dapanda?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&autoReconnect=True
    hikari:
      pool-name: Hikari
      auto-commit: false
  application:
    name: dapanda
  jpa:
    properties:
      hibernate:
        show-sql: 'true'
        format_sql: 'true'
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.MySQLDialect
cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2 # AWS SQS의 리전정보
    stack:
      auto: false
    sqs:
      queue:
        name: ${SQS_NAME}	# AWS에서 생성한 Queue 이름
        url: ${SQS_URL}		# AWS에서 생성한 Queue URL
